filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "name"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  setup.template:
    name: "filebeat"
    pattern: "filebeat-*"
    overwrite: true
setup.ilm:
  enabled: false